### ISSUE TITLE
what tool can draw this jpg

### ISSUE THREAD

**Issue by cucy** [rachit-ranjan16/Kiera#17]
hello , what tool when  you draw this pic
 https://raw.githubusercontent.com/rachit-ranjan16/Kiera/e0c97602cc757368ef63499ff27225d7c13e2cf7/design/ComponentDiag.png

**Comment by rachit-ranjan16** [comment]
Refer this for design details
https://github.com/rachit-ranjan16/Kiera/tree/master/design

**Comment by cucy** [comment]
Thanks!
